# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'ubuntu-16.04'

trigger:
  batch: true
  branches:
    include:
      - master
      - test-deploy
      - refs/tags/*

jobs:

  - deployment: Deploy
    displayName: Deploy to PyPI
    environment: deploy-env
    strategy:
      runOnce:
        deploy:
          steps:
            - task: UsePythonVersion@0
              displayName: 'Select Python Version 3.7'
              inputs:
                versionSpec: '3.7'
                architecture: 'x64'

            - script: |
                ls

            - script: pip install -r requirements.txt
              displayName: 'Install Python Dependencies'

            - script: |
                echo -e "[pypi]" >> ~/.pypirc
                echo -e "username = __token__" >> ~/.pypirc
                echo -e "password = $(PYPI_TOKEN)" >> ~/.pypirc
              displayName: 'Create ~/.pypirc for auth tokens'

            - script: |
                python setup.py sdist
                python setup.py bdist_wheel
              displayName: 'Build Package'

            - script: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
